### ISSUE TITLE
New release is broken for new installs

### ISSUE THREAD

**Issue by aidanlister** [MnogoByte/django-permanent#47]
See commit 11d236867971df1de69981c6025eab728f8fc848 which I don't think is valid.

**Comment by generalov** [comment]
Perhaps there is a fix https://github.com/bor3ham/django-permanent/commit/08456f42c7721b44cd41b0b1b8d6494e1257d705 . 
Don't try to import the `django` package in the `setup.py` because that package may not be installed yet.
It is not a good idea to check django version in the installation process. The django can be upgraded after django-permanent installation.
It's better to describe the exact configuration with package versions externally (in the requirements.txt, .travis.yml, and etc.), then check conditions during app initialization.

**Comment by meteozond** [comment]
Got it, going to fix it soon

**Comment by meteozond** [comment]
fixed by #48
